# Production Environment Configuration
# Optimized for production workloads with high availability and resources

celeryWorker:
  replicaCount: 10
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "2000m"

redis:
  persistence:
    enabled: true
    size: 20Gi
    storageClass: fast-ssd  # Use fast storage for production
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

fenicsx:
  resources:
    requests:
      memory: "2Gi"
      cpu: "2000m"
    limits:
      memory: "32Gi"
      cpu: "16000m"

lammps:
  resources:
    requests:
      memory: "2Gi"
      cpu: "2000m"
    limits:
      memory: "32Gi"
      cpu: "16000m"

openfoam:
  resources:
    requests:
      memory: "2Gi"
      cpu: "2000m"
    limits:
      memory: "32Gi"
      cpu: "16000m"

# Production-grade affinity rules
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - celery-worker
        topologyKey: kubernetes.io/hostname
