---
apiVersion: v1
kind: ConfigMap
metadata:
  name: celery-config
  namespace: keystone
  labels:
    app: celery-worker
data:
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
  PYTHONUNBUFFERED: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: keystone
  labels:
    app: celery-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: keystone-celery-worker:latest
        imagePullPolicy: Never  # Use local images
        envFrom:
        - configMapRef:
            name: celery-config
        volumeMounts:
        - name: data
          mountPath: /data
        - name: celery-app
          mountPath: /app/celery_app.py
          subPath: celery_app.py
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: data
        hostPath:
          path: /data
          type: Directory
      - name: celery-app
        hostPath:
          path: /home/runner/work/KeystoneSupercomputer/KeystoneSupercomputer/src/celery_app.py
          type: File
