# Default values for keystone-simulation.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global settings
global:
  namespace: keystone
  imagePullPolicy: Never  # Use local images for development

# Redis configuration
redis:
  enabled: true
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6379
  persistence:
    enabled: true
    storageClass: ""
    size: 1Gi
    accessMode: ReadWriteOnce
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5

# Celery worker configuration
celeryWorker:
  enabled: true
  replicaCount: 2
  image:
    repository: keystone-celery-worker
    tag: latest
    pullPolicy: Never
  config:
    brokerUrl: "redis://redis:6379/0"
    resultBackend: "redis://redis:6379/0"
  volumes:
    dataPath: /data
    celeryAppPath: /home/runner/work/KeystoneSupercomputer/KeystoneSupercomputer/src/celery_app.py
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

# FEniCSx simulation tool configuration
fenicsx:
  enabled: true
  image:
    repository: fenicsx-toolbox
    tag: latest
    pullPolicy: Never
  jobTemplate:
    suspend: true  # Don't run automatically
  config:
    simulationType: "fenicsx"
  volumes:
    dataPath: /data/fenicsx
    scriptsPath: /home/runner/work/KeystoneSupercomputer/KeystoneSupercomputer/src/sim-toolbox/fenicsx
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

# LAMMPS simulation tool configuration
lammps:
  enabled: true
  image:
    repository: keystone/lammps
    tag: latest
    pullPolicy: Never
  jobTemplate:
    suspend: true  # Don't run automatically
  config:
    simulationType: "lammps"
  volumes:
    dataPath: /data/lammps
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

# OpenFOAM simulation tool configuration
openfoam:
  enabled: true
  image:
    repository: openfoam-toolbox
    tag: latest
    pullPolicy: Never
  jobTemplate:
    suspend: true  # Don't run automatically
  config:
    simulationType: "openfoam"
    foamRun: "/workspace/foam-run"
  volumes:
    dataPath: /data/openfoam
    workspacePath: /home/runner/work/KeystoneSupercomputer/KeystoneSupercomputer/src/sim-toolbox/openfoam
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

# Node selector for all pods
nodeSelector: {}

# Tolerations for all pods
tolerations: []

# Affinity for all pods
affinity: {}
